import {Scene,Mesh,MeshBuilder,StandardMaterial,DynamicTexture,Color3,Vector3,Matrix,Quaternion,Camera} from './babylon';
import {BattleEvent,randomGenerator} from '../core/types';
import {heightAt} from '../core/map';
import {Simulation} from '../core/simulation';
interface Particle{x:number;y:number;z:number;vx:number;vy:number;vz:number;life:number;max:number;size:number;grow:number;color:number[];kind:number;angle:number}
interface Tracer{a:Vector3;b:Vector3;life:number;max:number;rocket:boolean;team:number}
export class Effects{
 particles:Particle[]=[];tracers:Tracer[]=[];quality=1;private random=randomGenerator(837);private smoke:Mesh;private flash:Mesh;private line:Mesh;private mark:Mesh;private markLife=0;
 private buffers=[new Float32Array(400*16),new Float32Array(400*16),new Float32Array(160*16)];private colors=[new Float32Array(400*4),new Float32Array(400*4),new Float32Array(160*4)];private m=Matrix.Identity();private q=Quaternion.Identity();private dustTimer=0;
 constructor(readonly scene:Scene){
  const texture=new DynamicTexture('soft dust',{width:64,height:64},scene,false);const ctx=texture.getContext();const gradient=ctx.createRadialGradient(32,32,0,32,32,31);gradient.addColorStop(0,'rgba(255,255,255,.8)');gradient.addColorStop(.4,'rgba(255,255,255,.48)');gradient.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);texture.hasAlpha=true;texture.update();
  const glow=new DynamicTexture('muzzle star',{width:64,height:64},scene,false);const c=glow.getContext();c.clearRect(0,0,64,64);const g=c.createRadialGradient(32,32,0,32,32,30);g.addColorStop(0,'rgba(255,255,232,1)');g.addColorStop(.13,'rgba(255,224,112,1)');g.addColorStop(.4,'rgba(255,174,49,.6)');g.addColorStop(1,'rgba(255,130,20,0)');c.fillStyle=g;c.fillRect(0,0,64,64);c.fillStyle='rgba(255,246,185,.9)';c.beginPath();c.moveTo(32,8);c.lineTo(36,27);c.lineTo(56,32);c.lineTo(37,36);c.lineTo(32,56);c.lineTo(28,37);c.lineTo(8,32);c.lineTo(27,28);c.fill();glow.hasAlpha=true;glow.update();
  this.smoke=MeshBuilder.CreatePlane('pooled dust',{size:1},scene);this.flash=MeshBuilder.CreatePlane('pooled muzzle flashes',{size:1},scene);this.line=MeshBuilder.CreateCylinder('pooled tracers',{diameter:1,height:1,tessellation:4},scene);
  [this.smoke,this.flash,this.line].forEach((mesh,i)=>{const mat=new StandardMaterial('effect '+i,scene);mat.disableLighting=true;mat.emissiveColor=Color3.White();mat.diffuseColor=Color3.White();mat.backFaceCulling=false;mat.disableDepthWrite=true;if(i<2){mat.diffuseTexture=i===0?texture:glow;mat.useAlphaFromDiffuseTexture=true;mat.transparencyMode=2;mat.alphaMode=i===0?2:1;}mesh.material=mat;mesh.hasVertexAlpha=true;mesh.isPickable=false;mesh.alwaysSelectAsActiveMesh=true;mesh.thinInstanceSetBuffer('matrix',this.buffers[i],16,false);mesh.thinInstanceSetBuffer('instanceColor',this.colors[i],4,false);mesh.thinInstanceCount=0;mesh.renderingGroupId=1;});
  this.mark=MeshBuilder.CreateTorus('order acknowledgement',{diameter:3,thickness:.08,tessellation:40},scene);const mat=new StandardMaterial('order light',scene);mat.disableLighting=true;mat.emissiveColor=Color3.FromHexString('#9ae8cc');this.mark.material=mat;this.mark.isPickable=false;this.mark.setEnabled(false);
 }
 order(x:number,z:number){this.mark.position.set(x,heightAt(x,z)+.16,z);this.markLife=1;this.mark.setEnabled(true);}
 private spawn(x:number,y:number,z:number,kind:number,size:number,life:number,color:number[],vx=0,vy=0,vz=0,grow=1){if(this.particles.length>Math.floor(220*this.quality))return;this.particles.push({x,y,z,kind,size,life,max:life,color,vx,vy,vz,grow,angle:this.random()*6.28});}
 private burst(x:number,z:number,big=false){const y=heightAt(x,z);this.spawn(x,y+1,z,1,big?7:2.3,.22,[1,.72,.23,1],0,0,0,12);const n=Math.round((big?22:7)*this.quality);for(let i=0;i<n;i++){const a=this.random()*6.28,v=this.random()*(big?8:3);this.spawn(x,y+.2,z,0,big?2.6:.8,(big?2.5:1.2)+this.random(),[.54,.45,.31,.55],Math.cos(a)*v,.7+this.random()*2,Math.sin(a)*v,big?3:1.3);if(i<6)this.spawn(x,y+.5,z,1,.14,.25+this.random()*.2,[1,.83,.43,1],Math.cos(a)*v*2,1+this.random()*4,Math.sin(a)*v*2,-.1);}
 }
 event(e:BattleEvent){
  if(e.type==='shot'&&e.tx!==undefined&&e.tz!==undefined){const rocket=e.role==='at',vehicle=e.role==='vehicle',y=heightAt(e.x,e.z)+(vehicle?2.8:1.7),a=new Vector3(e.x,y,e.z),b=new Vector3(e.tx,heightAt(e.tx,e.tz)+1.2,e.tz);this.tracers.push({a,b,life:rocket?.5:.095,max:rocket?.5:.095,rocket,team:e.team});this.spawn(e.x,y,e.z,1,vehicle?2.1:rocket?1.8:1.05,.095,[1,.88,.54,1]);if(rocket)this.spawn(e.x,y-.5,e.z,0,1.5,1.4,[.66,.61,.47,.4],-.6,.8,-.6,2);}
  if(e.type==='impact'){if(e.role==='at')this.burst(e.x,e.z);else{this.spawn(e.x,heightAt(e.x,e.z)+.3,e.z,0,.5,.65,[.62,.49,.33,.4],.3,.7,.1,1.7);this.spawn(e.x,heightAt(e.x,e.z)+1,e.z,1,.35,.1,[1,.85,.45,1]);}}
  if(e.type==='death'&&e.role==='vehicle')this.burst(e.x,e.z,true);
 }
 update(dt:number,time:number,camera:Camera,sim:Simulation){
  this.dustTimer-=dt;if(this.dustTimer<0){this.dustTimer=.15/this.quality;for(const q of sim.squads){if(q.dead||q.speed<1||!sim.visible(q))continue;if(q.role==='vehicle'){const x=q.x-Math.sin(q.angle)*2,z=q.z-Math.cos(q.angle)*2;this.spawn(x,heightAt(x,z)+.3,z,0,1.4,1.7,[.62,.52,.36,.32],-.3,.5,.2,1.9);}else if(this.random()<.3)this.spawn(q.x,heightAt(q.x,q.z)+.1,q.z,0,.6,.75,[.59,.49,.35,.23],.1,.2,.1,.7);}}
  const counts=[0,0,0];const rotation=camera.absoluteRotation;
  for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.life-=dt;if(p.life<=0){this.particles.splice(i,1);continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.size+=p.grow*dt;p.vx*=1-dt*.9;p.vz*=1-dt*.9;const kind=p.kind,index=counts[kind]++;if(index>=400)continue;Quaternion.RotationYawPitchRollToRef(0,0,p.angle,this.q);this.q=rotation.multiply(this.q);Matrix.ComposeToRef(new Vector3(p.size,p.size,p.size),this.q,new Vector3(p.x,p.y,p.z),this.m);this.m.copyToArray(this.buffers[kind],index*16);const alpha=p.color[3]*Math.sin(Math.PI*Math.min(1,p.life/p.max))*(kind===1?1.7:1);this.colors[kind].set([p.color[0],p.color[1],p.color[2],alpha],index*4);}
  for(let i=this.tracers.length-1;i>=0;i--){const t=this.tracers[i];t.life-=dt;if(t.life<=0){this.tracers.splice(i,1);continue;}if(counts[2]>=160)continue;const pct=1-t.life/t.max,a=Vector3.Lerp(t.a,t.b,Math.max(0,pct-(t.rocket?.05:.26))),b=Vector3.Lerp(t.a,t.b,Math.min(1,pct+.15));const d=b.subtract(a);Quaternion.FromUnitVectorsToRef(Vector3.Up(),d.normalizeToNew(),this.q);Matrix.ComposeToRef(new Vector3(t.rocket?.16:.045,d.length(),t.rocket?.16:.045),this.q,a.add(b).scale(.5),this.m);this.m.copyToArray(this.buffers[2],counts[2]*16);this.colors[2].set(t.team===0?[1,.9,.51,1]:[1,.64,.33,1],counts[2]*4);counts[2]++;if(t.rocket&&this.random()<.7)this.spawn(a.x,a.y,a.z,0,.45,.8,[.67,.64,.55,.36],0,.35,0,.8);}
  [this.smoke,this.flash,this.line].forEach((mesh,i)=>{mesh.setEnabled(counts[i]>0);mesh.thinInstanceCount=counts[i];if(counts[i]){mesh.thinInstanceBufferUpdated('matrix');mesh.thinInstanceBufferUpdated('instanceColor');}});
  this.markLife-=dt;if(this.markLife>0){this.mark.scaling.setAll(1+(1-this.markLife)*1.4);(this.mark.material as StandardMaterial).alpha=this.markLife;}else this.mark.setEnabled(false);
 }
}
